package com.redhat.ceylon.eclipse.code.parse;

import java.util.List;

public interface IAnnotationTypeInfo extends org.eclipse.imp.services.IAnnotationTypeInfo {
    /**
     * Add a type of problem marker to the list of problem marker
     * types to which errors generated by this parser may correspond.
     * 
     * @param problemMarkerType The name of the problem marker type
     */
    public void addProblemMarkerType(String problemMarkerType);

    /**
     * Provide the list of problem marker types to which errors
     * generated by this parser may correspond.
     * 
     * @return  The list of problem marker types
     */
    public List<String> getProblemMarkerTypes();

    /**
     * Remove a type of problem marker from the list of problem marker
     * types to which errors generated by this parser may correspond.
     * 
     * @param problemMarkerType The name of the problem marker type
     */
    public void removeProblemMarkerType(String problemMarkerType);
}